[package]
name = "rusty-gpt2"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
tiktoken-rs = "0.7.0"
safetensors = "0.6.2"
bytemuck = "1.24"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libm = "0.2"
